// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnfwxAex-JSGAJ6BZRD1ooxbdn9Oms7GE',
    appId: '1:1049404009330:android:b48398c53985ba5e3c0beb',
    messagingSenderId: '1049404009330',
    projectId: 'taaf-5ef6b',
    storageBucket: 'taaf-5ef6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8qEzgGtdtnATDHTyXqbzoX_tFxbBxbM',
    appId: '1:1049404009330:ios:1f41f6ace93b88c33c0beb',
    messagingSenderId: '1049404009330',
    projectId: 'taaf-5ef6b',
    storageBucket: 'taaf-5ef6b.appspot.com',
    androidClientId: '1049404009330-jbt1dolgbc18bghi7dkdpt6kjajrviol.apps.googleusercontent.com',
    iosClientId: '1049404009330-afn3hnamlqr226jm0613g9a4mprafccd.apps.googleusercontent.com',
    iosBundleId: 'com.example.taaf.com',
  );
}
